language: ruby
rvm:
- 2.2.2

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./cibuild.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
